### ISSUE TITLE
Inconsistent Names

### ISSUE THREAD

**Issue by cmgraz** [ChrisMuir/MMA-Data-Scrape#3] opened 2017-01-14 23:12 UTC
Again, not sure if I should open up new issues as this isn't related any coding error, but there are issues with names.

As would be expected with a user contributed site like wikipedia, names are typed differently from time to time.  

Georges St-Pierre vs Georges St. Pierre.  
James Te Huna vs James Te-Huna

I'm manually going through and making changes now, but I don't know if this is of any use to the actual scrape itself.

**Comment by cmgraz** [comment] 2017-01-14 23:31
I'll be honest.  Unfortunately, a scrape like this where I need names to match, I don't know if Wikipedia should be the focal point of a scrape.

It's difficult to consolidate any of this into a database when the originating identifier for a fighter (their name) are inconsistent throughout.  Through all the fights, there are over 800+ instances where fighter names from the events don't match the fighters scrape.  Far too many to manually fix.

Have you considered attempting to apply this scrape to a more robust database like sherdog's?

**Comment by ChrisMuir** [comment] 2017-01-15 05:17
"Again, not sure if I should open up new issues as this isn't related any coding error, but..."

First, just want to say that I very much appreciate issues being opened like this one. Getting this type of feedback from users like you is invaluable, so thank you.

I understand where you're coming from on the name matching. I will work on this some this week. I've only ever used the data to look at macro level trends, so never noticed there being multiple spellings for fighter names....again, thanks for bringing it to my attention.

And yes, I have considered using Sherdog. I'm reluctant to start from scratch on this, however it would probably be worthwhile....just a matter of finding the time.

**Comment by cmgraz** [comment] 2017-01-15 05:30
Yeah, I suppose it depends on your needs.  But there were too many issues.  Some weren't terribly far off, but there were punctuation differences, there were some shortened first names, there were some middle name inclusions, and also some nicknames.  To manually go through and try to match up the bout names to the fighter list was a losing battle.  And a good chunk of fighters don't have a wiki profile page which created issues too.  I'm confident each participant in any UFC event is listed in the sherdog fighter database.  

Starting from scratch would suck.  But then again,  I'm not sure of your programming skills, and there are plenty of python scrapers for sherdog on github.  Many are outdated, but can still provide a starting point.

This one is to scrape fighters and is still 100% working.
https://github.com/paddycarey/sherdog-fighter-scraper

The above scrapes only fighters.  Problem is, there are an insane # of fighters in their database.  I don't know if there are missing entries, but I can say from running this, I got up to ID 2218 and I had accrued 2178 rows of fighters.  

It also ran slow.  That took me an hour. 

I'd say it make more sense to scrape the UFC bouts first, and then only scrape the participants involved.

Wish I had any idea how to code this or I'd be on it.  But unfortunately, I'm only here to give opinions.

**Comment by cmgraz** [comment] 2017-01-18 08:05
Here's some food for thought.  Could resolve the name issue pending the difficulty to code.

For reach fighter that is being scraped in a bout that had a wiki profile, instead of taking the text, take the end of the URL of their fighter profile and make that the name.  

If done, even if names are typed differently, the text in the links will still be the same.

**Comment by ChrisMuir** [comment] 2017-01-18 15:21
Thanks for the thought, however that will not work, as the text within the fighter links from the fight results tables often follows how the name is spelled for that particular fight. To use one of the examples you raised, we see two different urls for GSP (each one points to the same GSP page):
https://en.wikipedia.org/wiki/Georges_St-Pierre
https://en.wikipedia.org/wiki/Georges_St._Pierre

When you first brought up the names issue, I noticed that within the fighters DB, there are indeed two entries for GSP (and James Te Huna, etc).

My plan to address the issue is to merge the two scrape jobs into one executable R file, and to have names for the bouts dataframe get sourced from the fighters dataframe. This will obviously only cover instances in which the fighter has a wiki page, but it will certainly be an improvement. I will also include a step to eliminate duplicates within the fighter dataframe.

**Comment by cmgraz** [comment] 2017-01-18 15:44
I guess the other idea would then be to grab the text from the ("h1",
{"id": "firstHeading"}) off of the wiki link associated with each fighter.
In the case of GSP:

https://en.wikipedia.org/wiki/Georges_St-Pierre
https://en.wikipedia.org/wiki/Georges_St._Pierre

both are directed to the same page, so the "firstHeading" for both is the
same, "Georges St-Pierre".  As long as the links are correct, this class
will always derive the same name.

I guess I'm confused what your idea does.  Doesn't the fighters dataframe
simply compile a list of fighters from the previous bout dataframe?  It
seems like in this case you're creating a bouts dataframe, making a
fighters dataframe from the bouts dataframe, then fixing the bouts
dataframe with information from the fighters dataframe.  Because fighters
dataframe is derived from bouts, can't the issue on the bouts dataframe be
resolved within itself rather than merging two scrapes into another file?

Maybe I'm way off on how this is all working.

**Comment by ChrisMuir** [comment] 2017-01-19 01:57
You are correct in your assessment of the flow.....the bouts dataframe gets compiled first, during this process every fighter wiki link that appears in each events page is recorded, and the fighter dataframe gets created from that list of fighter wiki links. 

What I have in mind is to merge the two step process into one step....the fighter df would get built along side the bouts df. I'll be doing what you suggest (pulling the HTML of a fighter while the bouts df is being built in order to get the correct name), but instead of only grabbing the name, I'll take all of the data from the fighter page and add it to the fighter df as a new observation.

**Comment by ChrisMuir** [comment] 2017-03-10 05:07
Just pushed changes that address this issue. I created an R package ([refinr](https://github.com/ChrisMuir/refinr)) that clusters and merges similar values within a character vector. I've added those functions to both scrape files within this repo, which fixes the inconsistent names issue.

The commit is [here](https://github.com/ChrisMuir/MMA-Data-Scrape/commit/72f3dbd79ecf09eeb59507f0229323b79d65e1e4). I'm closing this issue.

Thanks again @cmgraz for bringing this to my attention in the first place.

**Closed as completed** 2017-03-10 05:09 UTC
